//! Provenance tracking for memory origins and derivation chains

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::{AgentId, MemoryId, SessionId};

/// Complete provenance information for a memory
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Provenance {
    /// The source of this memory
    pub source: Source,
    /// Chain of derivations (if derived from other memories)
    pub derivations: Vec<Derivation>,
    /// When this memory was created
    pub created_at: DateTime<Utc>,
    /// When this memory was last modified
    pub modified_at: DateTime<Utc>,
    /// When this memory was last accessed
    pub last_accessed_at: DateTime<Utc>,
    /// Number of times this memory has been accessed
    pub access_count: u64,
    /// The agent that created this memory
    pub created_by: AgentId,
    /// Session in which this memory was created (if applicable)
    pub session_id: Option<SessionId>,
}

impl Provenance {
    /// Create new provenance for a directly observed/created memory
    pub fn new_direct(source: Source, agent_id: AgentId) -> Self {
        let now = Utc::now();
        Self {
            source,
            derivations: Vec::new(),
            created_at: now,
            modified_at: now,
            last_accessed_at: now,
            access_count: 0,
            created_by: agent_id,
            session_id: None,
        }
    }

    /// Create provenance for a derived memory
    pub fn new_derived(source: Source, derivations: Vec<Derivation>, agent_id: AgentId) -> Self {
        let now = Utc::now();
        Self {
            source,
            derivations,
            created_at: now,
            modified_at: now,
            last_accessed_at: now,
            access_count: 0,
            created_by: agent_id,
            session_id: None,
        }
    }

    /// Set the session ID
    pub fn with_session(mut self, session_id: SessionId) -> Self {
        self.session_id = Some(session_id);
        self
    }

    /// Record an access to this memory
    pub fn record_access(&mut self) {
        self.last_accessed_at = Utc::now();
        self.access_count += 1;
    }

    /// Record a modification to this memory
    pub fn record_modification(&mut self) {
        self.modified_at = Utc::now();
    }

    /// Add a derivation to the chain
    pub fn add_derivation(&mut self, derivation: Derivation) {
        self.derivations.push(derivation);
        self.modified_at = Utc::now();
    }

    /// Check if this memory is derived from another
    pub fn is_derived_from(&self, memory_id: &MemoryId) -> bool {
        self.derivations
            .iter()
            .any(|d| d.source_memories.contains(memory_id))
    }

    /// Get the age of this memory
    pub fn age(&self) -> chrono::Duration {
        Utc::now() - self.created_at
    }

    /// Get time since last access
    pub fn time_since_access(&self) -> chrono::Duration {
        Utc::now() - self.last_accessed_at
    }
}

/// The original source of a memory
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Source {
    /// Directly from user interaction
    UserInput {
        /// Raw input text
        input: String,
        /// Context about when/how it was received
        context: Option<String>,
    },
    /// From an external API or service
    ExternalApi {
        /// Name of the API/service
        service: String,
        /// Endpoint or resource
        endpoint: Option<String>,
        /// Request ID for tracing
        request_id: Option<String>,
    },
    /// From a document or file
    Document {
        /// Path or identifier
        path: String,
        /// Document type (pdf, md, etc.)
        doc_type: Option<String>,
        /// Specific section or page
        location: Option<String>,
    },
    /// Generated by the agent itself
    AgentGenerated {
        /// The process that generated this
        process: String,
        /// Additional context
        context: Option<String>,
    },
    /// From another agent
    AgentShared {
        /// The sharing agent
        source_agent: AgentId,
        /// Original memory ID in the source agent
        original_id: MemoryId,
    },
    /// Consolidated from multiple sources
    Consolidated {
        /// Number of source memories
        source_count: usize,
        /// Consolidation method used
        method: String,
    },
    /// Imported from external system
    Import {
        /// System name
        system: String,
        /// Import timestamp
        imported_at: DateTime<Utc>,
    },
    /// Unknown or unspecified source
    Unknown,
}

impl Source {
    /// Create a user input source
    pub fn user_input(input: impl Into<String>) -> Self {
        Self::UserInput {
            input: input.into(),
            context: None,
        }
    }

    /// Create an agent-generated source
    pub fn agent_generated(process: impl Into<String>) -> Self {
        Self::AgentGenerated {
            process: process.into(),
            context: None,
        }
    }

    /// Create a document source
    pub fn document(path: impl Into<String>) -> Self {
        Self::Document {
            path: path.into(),
            doc_type: None,
            location: None,
        }
    }

    /// Get a human-readable description of the source
    pub fn description(&self) -> String {
        match self {
            Source::UserInput { .. } => "User input".to_string(),
            Source::ExternalApi { service, .. } => format!("API: {}", service),
            Source::Document { path, .. } => format!("Document: {}", path),
            Source::AgentGenerated { process, .. } => format!("Generated: {}", process),
            Source::AgentShared { source_agent, .. } => format!("Shared from {}", source_agent),
            Source::Consolidated { source_count, .. } => {
                format!("Consolidated from {} memories", source_count)
            }
            Source::Import { system, .. } => format!("Imported from {}", system),
            Source::Unknown => "Unknown".to_string(),
        }
    }
}

/// A derivation step in the memory's history
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Derivation {
    /// The memories this was derived from
    pub source_memories: Vec<MemoryId>,
    /// The type of derivation
    pub derivation_type: DerivationType,
    /// When this derivation occurred
    pub derived_at: DateTime<Utc>,
    /// Additional context about the derivation
    pub context: Option<String>,
}

impl Derivation {
    /// Create a new derivation record
    pub fn new(source_memories: Vec<MemoryId>, derivation_type: DerivationType) -> Self {
        Self {
            source_memories,
            derivation_type,
            derived_at: Utc::now(),
            context: None,
        }
    }

    /// Add context to the derivation
    pub fn with_context(mut self, context: impl Into<String>) -> Self {
        self.context = Some(context.into());
        self
    }
}

/// Types of derivation operations
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DerivationType {
    /// Extracted from a larger memory (e.g., fact from conversation)
    Extraction,
    /// Merged from multiple similar memories
    Merge,
    /// Summarized/abstracted from multiple memories
    Summary,
    /// Inferred from existing memories
    Inference,
    /// Contradiction resolution
    Resolution,
    /// Regular consolidation
    Consolidation,
    /// Distillation (episodic → semantic)
    Distillation,
    /// Manual edit by user/agent
    Edit,
    /// Split from a larger memory
    Split,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_access_tracking() {
        let mut prov = Provenance::new_direct(Source::user_input("test"), AgentId::new());

        assert_eq!(prov.access_count, 0);

        prov.record_access();
        assert_eq!(prov.access_count, 1);

        prov.record_access();
        assert_eq!(prov.access_count, 2);
    }

    #[test]
    fn derivation_chain() {
        let agent = AgentId::new();
        let source_ids = vec![MemoryId::new(), MemoryId::new()];

        let derivation = Derivation::new(source_ids.clone(), DerivationType::Merge)
            .with_context("Combined similar facts");

        let mut prov = Provenance::new_derived(
            Source::Consolidated {
                source_count: 2,
                method: "merge".to_string(),
            },
            vec![derivation],
            agent,
        );

        assert!(prov.is_derived_from(&source_ids[0]));
        assert!(prov.is_derived_from(&source_ids[1]));
        assert!(!prov.is_derived_from(&MemoryId::new()));

        // Add another derivation
        prov.add_derivation(Derivation::new(vec![MemoryId::new()], DerivationType::Edit));

        assert_eq!(prov.derivations.len(), 2);
    }

    #[test]
    fn source_descriptions() {
        assert_eq!(Source::user_input("test").description(), "User input");
        assert!(Source::AgentGenerated {
            process: "analysis".to_string(),
            context: None
        }
        .description()
        .contains("Generated"));
    }
}
